### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by iennae**
## Overview

Clean up the rubocop configuration so that folks can run rubocop. 

Previously was running into this issue

```
Jennifers-MBP:couchdb-cookbook sigje$ cookstyle
Inspecting 2 files


0 files inspected, no offenses detected
Error: No such file or directory: /Users/sigje/couchdb-cookbook/Layout/LeadingCommentSpace:
```

Once I renamed the file 

```
Jennifers-MBP:couchdb-cookbook sigje$ cookstyle
/Users/sigje/couchdb-cookbook/.rubocop.yml: Layout/LeadingCommentSpace has the wrong namespace - should be Style
Inspecting 21 files
.....................
```

Modifying Layout to Style cleaned up the issue

```
Jennifers-MBP:couchdb-cookbook sigje$ cookstyle
Inspecting 21 files
.....................

21 files inspected, no offenses detected

```

We recommend cookstyle as Rubocop can change and it's a way to have a consistent set of style guidelines across contributors specific to cookbooks. 

I also updated the contributing and testing documentation to reflect current cookbook style guidelines and to provide a little more help to new folks who might want to help out. 

## Testing recommendations

This is mostly a documentation fix. 

## Checklist

- [ ] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [x] Documentation reflects the changes;

### CODE REVIEW

**Comment by wohali** [comment]
Strange. I already was running cookstyle locally (though it's not in the Rakefile...). On `master`, I can't reproduce what you're seeing.

```bash
[joant@chefdev couchdb]$ cookstyle
Inspecting 0 files


0 files inspected, no offenses detected
[joant@chefdev couchdb]$ chef --version
Chef Development Kit Version: 1.4.3
chef-client version: 13.1.31
delivery version: master (41b94ffb5efd33723cf72a89bf4d273c8151c9dc)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1
[joant@chefdev couchdb]$ grep -i cookstyle Gemfile*
Gemfile:gem 'cookstyle'
Gemfile.lock:    cookstyle (2.0.0)
Gemfile.lock:  cookstyle
```

I'm loathe to merge this until I understand specifically what you're running into. Can you help me understand?

**Comment by wohali** [comment]
I think you must have an outdated version of cookstyle. The docs say [Layout/LeadingCommentSpace](http://rubocop.readthedocs.io/en/latest/cops_layout/#layoutleadingcommentspace) is correct. And I found [this commit](https://github.com/bbatsov/rubocop/commits/b11ef7741f38b7c23761695f5b3bcb7a0219dfeb/lib/rubocop/cop/layout/leading_comment_space.rb) from April that moves LeadingCommentSpace from Style to Layout.

Happy to merge the other changes if you can drop the .rubocop* changes. Thank you for helping! :)

**Comment by iennae** [comment]
I'm using the cookstyle that comes with the Chef DK versus installing it separately. I'll take a look at this and see whether a later version of Chef DK has changed this.

**Comment by wohali** [comment]
Looks like my mistake for installing the latest rubocop. The latest Chef DK ships with version 0.49.1:

https://github.com/chef/chef-dk/blob/master/Gemfile.lock#L681

Thanks for helping me get to the bottom of this!

**Pull request merged**
